%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Generate C++ code %%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%

codegen -c -d 'lib' -config:lib ...
	    qp_vars -args {zeros(n,1)} ...
	    kalman -args {zeros(3,1), zeros(3), zeros(2,1), zeros(1,1), 1} ...   
	    kalman_4d -args {zeros(4,1), zeros(4), zeros(2,1), zeros(1,1), 1}	 